module.exports = {
  
  TOKEN_SECRET: process.env.TOKEN_SECRET || 'mysecretsamuxyz',

  // OAuth 2.0
  FACEBOOK_SECRET: '3f1701a1d953b8dbd3552a446bba3bdd',
  GOOGLE_SECRET: 'DYEJTZggWC6715x6kQFcIpGm',
  GITHUB_SECRET: '168dd5304ad39e1a265cecf3763bb68875bb5b9b',
  LINKEDIN_SECRET: '5CTjLIeiliJNW1uc',
  /*FOURSQUARE_SECRET: process.env.FOURSQUARE_SECRET || 'YOUR_FOURSQUARE_CLIENT_SECRET',
  GOOGLE_SECRET: process.env.GOOGLE_SECRET || 'YOUR_GOOGLE_CLIENT_SECRET',
  GITHUB_SECRET: process.env.GITHUB_SECRET || 'YOUR_GITHUB_CLIENT_SECRET',
  INSTAGRAM_SECRET: process.env.INSTAGRAM_SECRET || 'YOUR_INSTAGRAM_CLIENT_SECRET',
  LINKEDIN_SECRET: process.env.LINKEDIN_SECRET || 'YOUR_LINKEDIN_CLIENT_SECRET',
  TWITCH_SECRET: process.env.TWITCH_SECRET || 'YOUR_TWITCH_CLIENT_SECRET',
  WINDOWS_LIVE_SECRET: process.env.WINDOWS_LIVE_SECRET || 'YOUR_MICROSOFT_CLIENT_SECRET',
  YAHOO_SECRET: process.env.YAHOO_SECRET || 'YOUR_YAHOO_CLIENT_SECRET',
  BITBUCKET_SECRET: process.env.YAHOO_SECRET || 'YOUR_BITBUCKET_CLIENT_SECRET',
	*/
  // OAuth 1.0
  TWITTER_KEY: 'GqJlAVW74dl10cP5tIDmiXKuU',
  TWITTER_SECRET: 'mWjgivlc98o6jyK5uneNNVTYhFHENK1ItD0RXR9VV3zqgGTOGB'
};